---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен иметь мобильную версию
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
implicit:
  - Сайт не должен нарушать законы РФ 
  - Сайт должен указывать актуальные цены и условия покупки, которые не должны изменяться после оформления заказа.
  - Сайт должен иметь удобный интерфейс для пользователя
  - Сайт должен поддержваться на различный браузерах
  - Меню и навигационные элементы должны быть простыми и доступными для пользователя
  - Возможность легкого обновления информации о товарах, ценах и акциях без необходимости внесения изменений в код
  - Уведомления о добавлении товара в корзину, оформлении заказа и других действиях должны быть интуитивно понятными и не отвлекать от основной задачи
  - 
